import re

with open('gas_project/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Change the select to an input with a datalist
old_html = """        <div class="input-group">
          <label>אטרקציה / תיאור</label>
          <select class="input" id="expSelect" onchange="toggleManualExpense()">
            <!-- Options generated by JS -->
          </select>
        </div>
        
        <!-- Hidden by default, shown if "אחר..." is selected -->
        <div class="input-group" id="manualExpGroup" style="display:none; margin-top:16px;">
          <label>פירוט (הזנה ידנית)</label>
          <input type="text" class="input" id="expNameManual" placeholder="על מה שילמנו?">
        </div>"""

new_html = """        <div class="input-group">
          <label>אטרקציה / תיאור</label>
          <input type="text" class="input" id="expSelect" list="expOptions" placeholder="בחר מהרשימה או הקלד חופשי">
          <datalist id="expOptions">
            <!-- Options generated by JS -->
          </datalist>
        </div>"""

html = html.replace(old_html, new_html)

# Also fix the JS for setupExpenseDropdown
old_js = """function setupExpenseDropdown() {
      const sel = id('expSelect');
      if (!sel) return;
      let opts = '<option value="" disabled selected>בחר/י מהרשימה...</option>';
      if(BANK) {
         BANK.forEach(a => { opts += `<option value="${a.title}">${a.title}</option>`; });
      }
      if(DAYS) {
         DAYS.forEach(d => {
            if(d.attractions) {
               d.attractions.forEach(a => { opts += `<option value="${a.title}">${a.title}</option>`; });
            }
         });
      }
      opts += '<option value="other">אחר (הזנה ידנית)</option>';
      sel.innerHTML = opts;
    }"""

new_js = """function setupExpenseDropdown() {
      const sel = id('expOptions');
      if (!sel) return;
      let opts = '';
      if(BANK) {
         BANK.forEach(a => { opts += `<option value="${a.title}"></option>`; });
      }
      if(DAYS) {
         DAYS.forEach(d => {
            if(d.attractions) {
               d.attractions.forEach(a => { opts += `<option value="${a.title}"></option>`; });
            }
         });
      }
      sel.innerHTML = opts;
    }"""

html = html.replace(old_js, new_js)

# Fix openExpenseModal
old_modal = """    function openExpenseModal() {
      id('expSelect').value = '';
      id('expNameManual').value = '';
      toggleManualExpense();
      id('expCzk').value = ''; 
      id('expIls').value = ''; 
      id('expNote').value = '';
      id('expenseModal').classList.add('show');
    }"""

new_modal = """    function openExpenseModal() {
      id('expSelect').value = '';
      id('expCzk').value = ''; 
      id('expIls').value = ''; 
      id('expNote').value = '';
      id('expenseModal').classList.add('show');
    }"""

html = html.replace(old_modal, new_modal)

# Fix saveExpense
old_save = """    function saveExpense() {
      let name = id('expSelect').value;
      if (name === 'other') {
        name = id('expNameManual').value.trim();
      }"""

new_save = """    function saveExpense() {
      let name = id('expSelect').value.trim();"""

html = html.replace(old_save, new_save)

# Remove toggleManualExpense
html = re.sub(r'    function toggleManualExpense\(\) \{[\s\S]*?\}\n', '', html)

with open('gas_project/index.html', 'w', encoding='utf-8') as f:
    f.write(html)

